services:
  - type: web_service
    name: 305 Workspace
    env: node
    region: oregon
    plan: starter
    branch: main
    buildCommand: npm ci
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
